/********************************************************************************
** Form generated from reading UI file 'level1.ui'
**
** Created by: Qt User Interface Compiler version 5.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LEVEL1_H
#define UI_LEVEL1_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_level1
{
public:
    QWidget *widget;
    QWidget *widget_2;
    QWidget *widget_3;
    QWidget *widget_4;
    QWidget *widget_5;
    QWidget *widget_6;
    QWidget *widget_7;
    QWidget *widget_8;
    QWidget *widget_9;
    QWidget *widget_10;
    QWidget *widget_11;
    QWidget *widget_12;
    QWidget *widget_13;
    QWidget *widget_14;
    QWidget *widget_15;
    QWidget *widget_16;
    QWidget *widget_17;
    QWidget *widget_18;
    QWidget *widget_19;
    QWidget *widget_20;
    QWidget *widget_21;
    QWidget *widget_22;
    QWidget *widget_23;
    QWidget *widget_24;
    QWidget *widget_25;
    QWidget *widget_26;
    QWidget *widget_27;
    QWidget *widget_28;
    QWidget *widget_29;
    QWidget *widget_30;
    QWidget *widget_31;
    QWidget *widget_32;
    QWidget *widget_33;
    QWidget *widget_34;
    QWidget *widget_35;
    QWidget *widget_36;
    QWidget *widget_37;
    QWidget *widget_38;
    QWidget *widget_39;
    QWidget *widget_40;
    QWidget *widget_41;
    QWidget *widget_42;
    QWidget *widget_43;
    QWidget *widget_44;
    QWidget *widget_45;
    QWidget *widget_46;
    QWidget *widget_47;
    QWidget *widget_48;
    QWidget *widget_49;
    QWidget *widget_50;
    QWidget *widget_51;
    QWidget *widget_52;
    QWidget *widget_53;
    QWidget *widget_54;
    QWidget *widget_55;
    QWidget *widget_56;
    QWidget *widget_57;
    QWidget *widget_58;
    QWidget *widget_59;
    QWidget *widget_60;
    QWidget *widget_61;
    QWidget *widget_62;
    QWidget *widget_63;
    QWidget *widget_64;
    QWidget *widget_65;
    QWidget *widget_66;
    QWidget *widget_67;
    QWidget *widget_68;
    QWidget *widget_69;
    QWidget *widget_70;
    QWidget *widget_71;
    QWidget *widget_72;
    QWidget *widget_73;
    QWidget *widget_74;
    QWidget *widget_75;
    QWidget *widget_76;
    QWidget *widget_77;
    QWidget *widget_78;
    QWidget *widget_79;
    QWidget *widget_80;
    QWidget *widget_81;
    QWidget *widget_82;
    QWidget *widget_83;
    QWidget *widget_84;
    QWidget *widget_85;
    QWidget *widget_86;
    QWidget *widget_87;
    QWidget *widget_88;
    QWidget *widget_89;
    QWidget *widget_90;
    QWidget *widget_91;
    QWidget *widget_92;
    QWidget *widget_93;
    QWidget *widget_94;
    QWidget *widget_95;
    QWidget *widget_96;
    QWidget *widget_97;
    QWidget *widget_98;
    QWidget *widget_99;
    QWidget *widget_100;
    QWidget *widget_101;
    QWidget *widget_102;
    QWidget *widget_103;
    QWidget *widget_104;
    QWidget *widget_105;
    QWidget *widget_106;
    QWidget *widget_107;
    QWidget *widget_108;
    QWidget *widget_109;
    QWidget *widget_110;
    QWidget *widget_111;
    QWidget *widget_112;
    QWidget *widget_113;
    QWidget *widget_114;
    QWidget *widget_115;
    QWidget *widget_116;
    QWidget *widget_117;
    QWidget *widget_118;
    QWidget *widget_119;
    QWidget *widget_120;
    QWidget *widget_121;
    QWidget *widget_122;
    QWidget *widget_123;
    QWidget *widget_124;
    QWidget *widget_125;
    QWidget *widget_126;
    QWidget *widget_127;
    QWidget *widget_128;
    QWidget *widget_129;
    QWidget *widget_130;
    QWidget *widget_131;
    QWidget *widget_132;
    QWidget *widget_133;
    QWidget *widget_134;
    QWidget *widget_135;
    QWidget *widget_136;
    QWidget *widget_137;
    QWidget *widget_138;
    QWidget *widget_139;
    QWidget *widget_140;
    QWidget *widget_141;

    void setupUi(QWidget *level1)
    {
        if (level1->objectName().isEmpty())
            level1->setObjectName(QStringLiteral("level1"));
        level1->resize(800, 600);
        level1->setStyleSheet(QStringLiteral("background-color: rgb(0, 0, 0);"));
        widget = new QWidget(level1);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(280, 320, 40, 40));
        widget->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_2 = new QWidget(level1);
        widget_2->setObjectName(QStringLiteral("widget_2"));
        widget_2->setGeometry(QRect(80, 240, 40, 40));
        widget_2->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_3 = new QWidget(level1);
        widget_3->setObjectName(QStringLiteral("widget_3"));
        widget_3->setGeometry(QRect(480, 320, 40, 40));
        widget_3->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_4 = new QWidget(level1);
        widget_4->setObjectName(QStringLiteral("widget_4"));
        widget_4->setGeometry(QRect(560, 360, 40, 40));
        widget_4->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_5 = new QWidget(level1);
        widget_5->setObjectName(QStringLiteral("widget_5"));
        widget_5->setGeometry(QRect(120, 40, 40, 40));
        widget_5->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_6 = new QWidget(level1);
        widget_6->setObjectName(QStringLiteral("widget_6"));
        widget_6->setGeometry(QRect(160, 320, 40, 40));
        widget_6->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_7 = new QWidget(level1);
        widget_7->setObjectName(QStringLiteral("widget_7"));
        widget_7->setGeometry(QRect(40, 0, 40, 40));
        widget_7->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_8 = new QWidget(level1);
        widget_8->setObjectName(QStringLiteral("widget_8"));
        widget_8->setGeometry(QRect(80, 560, 40, 40));
        widget_8->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_9 = new QWidget(level1);
        widget_9->setObjectName(QStringLiteral("widget_9"));
        widget_9->setGeometry(QRect(640, 320, 40, 40));
        widget_9->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_10 = new QWidget(level1);
        widget_10->setObjectName(QStringLiteral("widget_10"));
        widget_10->setGeometry(QRect(720, 560, 40, 40));
        widget_10->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_11 = new QWidget(level1);
        widget_11->setObjectName(QStringLiteral("widget_11"));
        widget_11->setGeometry(QRect(40, 560, 40, 40));
        widget_11->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_12 = new QWidget(level1);
        widget_12->setObjectName(QStringLiteral("widget_12"));
        widget_12->setGeometry(QRect(120, 560, 40, 40));
        widget_12->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_13 = new QWidget(level1);
        widget_13->setObjectName(QStringLiteral("widget_13"));
        widget_13->setGeometry(QRect(0, 480, 40, 40));
        widget_13->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_14 = new QWidget(level1);
        widget_14->setObjectName(QStringLiteral("widget_14"));
        widget_14->setGeometry(QRect(120, 80, 40, 40));
        widget_14->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_15 = new QWidget(level1);
        widget_15->setObjectName(QStringLiteral("widget_15"));
        widget_15->setGeometry(QRect(0, 520, 40, 40));
        widget_15->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_16 = new QWidget(level1);
        widget_16->setObjectName(QStringLiteral("widget_16"));
        widget_16->setGeometry(QRect(120, 120, 40, 40));
        widget_16->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_17 = new QWidget(level1);
        widget_17->setObjectName(QStringLiteral("widget_17"));
        widget_17->setGeometry(QRect(0, 560, 40, 40));
        widget_17->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_18 = new QWidget(level1);
        widget_18->setObjectName(QStringLiteral("widget_18"));
        widget_18->setGeometry(QRect(160, 280, 40, 40));
        widget_18->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_19 = new QWidget(level1);
        widget_19->setObjectName(QStringLiteral("widget_19"));
        widget_19->setGeometry(QRect(200, 560, 40, 40));
        widget_19->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_20 = new QWidget(level1);
        widget_20->setObjectName(QStringLiteral("widget_20"));
        widget_20->setGeometry(QRect(360, 40, 40, 40));
        widget_20->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_21 = new QWidget(level1);
        widget_21->setObjectName(QStringLiteral("widget_21"));
        widget_21->setGeometry(QRect(240, 40, 40, 40));
        widget_21->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_22 = new QWidget(level1);
        widget_22->setObjectName(QStringLiteral("widget_22"));
        widget_22->setGeometry(QRect(280, 120, 40, 40));
        widget_22->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_23 = new QWidget(level1);
        widget_23->setObjectName(QStringLiteral("widget_23"));
        widget_23->setGeometry(QRect(240, 320, 40, 40));
        widget_23->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_24 = new QWidget(level1);
        widget_24->setObjectName(QStringLiteral("widget_24"));
        widget_24->setGeometry(QRect(360, 200, 40, 40));
        widget_24->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_25 = new QWidget(level1);
        widget_25->setObjectName(QStringLiteral("widget_25"));
        widget_25->setGeometry(QRect(120, 240, 40, 40));
        widget_25->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_26 = new QWidget(level1);
        widget_26->setObjectName(QStringLiteral("widget_26"));
        widget_26->setGeometry(QRect(320, 200, 40, 40));
        widget_26->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_27 = new QWidget(level1);
        widget_27->setObjectName(QStringLiteral("widget_27"));
        widget_27->setGeometry(QRect(160, 120, 40, 40));
        widget_27->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_28 = new QWidget(level1);
        widget_28->setObjectName(QStringLiteral("widget_28"));
        widget_28->setGeometry(QRect(280, 400, 40, 40));
        widget_28->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_29 = new QWidget(level1);
        widget_29->setObjectName(QStringLiteral("widget_29"));
        widget_29->setGeometry(QRect(160, 40, 40, 40));
        widget_29->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_30 = new QWidget(level1);
        widget_30->setObjectName(QStringLiteral("widget_30"));
        widget_30->setGeometry(QRect(200, 40, 40, 40));
        widget_30->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_31 = new QWidget(level1);
        widget_31->setObjectName(QStringLiteral("widget_31"));
        widget_31->setGeometry(QRect(240, 480, 40, 40));
        widget_31->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_32 = new QWidget(level1);
        widget_32->setObjectName(QStringLiteral("widget_32"));
        widget_32->setGeometry(QRect(240, 400, 40, 40));
        widget_32->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_33 = new QWidget(level1);
        widget_33->setObjectName(QStringLiteral("widget_33"));
        widget_33->setGeometry(QRect(680, 160, 40, 40));
        widget_33->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_34 = new QWidget(level1);
        widget_34->setObjectName(QStringLiteral("widget_34"));
        widget_34->setGeometry(QRect(720, 160, 40, 40));
        widget_34->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_35 = new QWidget(level1);
        widget_35->setObjectName(QStringLiteral("widget_35"));
        widget_35->setGeometry(QRect(440, 0, 40, 40));
        widget_35->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_36 = new QWidget(level1);
        widget_36->setObjectName(QStringLiteral("widget_36"));
        widget_36->setGeometry(QRect(440, 80, 40, 40));
        widget_36->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_37 = new QWidget(level1);
        widget_37->setObjectName(QStringLiteral("widget_37"));
        widget_37->setGeometry(QRect(440, 160, 40, 40));
        widget_37->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_38 = new QWidget(level1);
        widget_38->setObjectName(QStringLiteral("widget_38"));
        widget_38->setGeometry(QRect(360, 120, 40, 40));
        widget_38->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_39 = new QWidget(level1);
        widget_39->setObjectName(QStringLiteral("widget_39"));
        widget_39->setGeometry(QRect(80, 360, 40, 40));
        widget_39->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_40 = new QWidget(level1);
        widget_40->setObjectName(QStringLiteral("widget_40"));
        widget_40->setGeometry(QRect(400, 160, 40, 40));
        widget_40->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_41 = new QWidget(level1);
        widget_41->setObjectName(QStringLiteral("widget_41"));
        widget_41->setGeometry(QRect(400, 40, 40, 40));
        widget_41->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_42 = new QWidget(level1);
        widget_42->setObjectName(QStringLiteral("widget_42"));
        widget_42->setGeometry(QRect(360, 160, 40, 40));
        widget_42->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_43 = new QWidget(level1);
        widget_43->setObjectName(QStringLiteral("widget_43"));
        widget_43->setGeometry(QRect(160, 560, 40, 40));
        widget_43->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_44 = new QWidget(level1);
        widget_44->setObjectName(QStringLiteral("widget_44"));
        widget_44->setGeometry(QRect(200, 320, 40, 40));
        widget_44->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_45 = new QWidget(level1);
        widget_45->setObjectName(QStringLiteral("widget_45"));
        widget_45->setGeometry(QRect(80, 400, 40, 40));
        widget_45->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_46 = new QWidget(level1);
        widget_46->setObjectName(QStringLiteral("widget_46"));
        widget_46->setGeometry(QRect(160, 240, 40, 40));
        widget_46->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_47 = new QWidget(level1);
        widget_47->setObjectName(QStringLiteral("widget_47"));
        widget_47->setGeometry(QRect(480, 160, 40, 40));
        widget_47->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_48 = new QWidget(level1);
        widget_48->setObjectName(QStringLiteral("widget_48"));
        widget_48->setGeometry(QRect(80, 320, 40, 40));
        widget_48->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_49 = new QWidget(level1);
        widget_49->setObjectName(QStringLiteral("widget_49"));
        widget_49->setGeometry(QRect(520, 160, 40, 40));
        widget_49->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_50 = new QWidget(level1);
        widget_50->setObjectName(QStringLiteral("widget_50"));
        widget_50->setGeometry(QRect(640, 160, 40, 40));
        widget_50->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_51 = new QWidget(level1);
        widget_51->setObjectName(QStringLiteral("widget_51"));
        widget_51->setGeometry(QRect(520, 120, 40, 40));
        widget_51->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_52 = new QWidget(level1);
        widget_52->setObjectName(QStringLiteral("widget_52"));
        widget_52->setGeometry(QRect(680, 560, 40, 40));
        widget_52->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_53 = new QWidget(level1);
        widget_53->setObjectName(QStringLiteral("widget_53"));
        widget_53->setGeometry(QRect(600, 560, 40, 40));
        widget_53->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_54 = new QWidget(level1);
        widget_54->setObjectName(QStringLiteral("widget_54"));
        widget_54->setGeometry(QRect(400, 560, 40, 40));
        widget_54->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_55 = new QWidget(level1);
        widget_55->setObjectName(QStringLiteral("widget_55"));
        widget_55->setGeometry(QRect(560, 160, 40, 40));
        widget_55->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_56 = new QWidget(level1);
        widget_56->setObjectName(QStringLiteral("widget_56"));
        widget_56->setGeometry(QRect(600, 160, 40, 40));
        widget_56->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_57 = new QWidget(level1);
        widget_57->setObjectName(QStringLiteral("widget_57"));
        widget_57->setGeometry(QRect(560, 280, 40, 40));
        widget_57->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_58 = new QWidget(level1);
        widget_58->setObjectName(QStringLiteral("widget_58"));
        widget_58->setGeometry(QRect(560, 320, 40, 40));
        widget_58->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_59 = new QWidget(level1);
        widget_59->setObjectName(QStringLiteral("widget_59"));
        widget_59->setGeometry(QRect(600, 320, 40, 40));
        widget_59->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_60 = new QWidget(level1);
        widget_60->setObjectName(QStringLiteral("widget_60"));
        widget_60->setGeometry(QRect(640, 560, 40, 40));
        widget_60->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_61 = new QWidget(level1);
        widget_61->setObjectName(QStringLiteral("widget_61"));
        widget_61->setGeometry(QRect(440, 560, 40, 40));
        widget_61->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_62 = new QWidget(level1);
        widget_62->setObjectName(QStringLiteral("widget_62"));
        widget_62->setGeometry(QRect(240, 560, 40, 40));
        widget_62->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_63 = new QWidget(level1);
        widget_63->setObjectName(QStringLiteral("widget_63"));
        widget_63->setGeometry(QRect(480, 560, 40, 40));
        widget_63->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_64 = new QWidget(level1);
        widget_64->setObjectName(QStringLiteral("widget_64"));
        widget_64->setGeometry(QRect(280, 560, 40, 40));
        widget_64->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_65 = new QWidget(level1);
        widget_65->setObjectName(QStringLiteral("widget_65"));
        widget_65->setGeometry(QRect(520, 560, 40, 40));
        widget_65->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_66 = new QWidget(level1);
        widget_66->setObjectName(QStringLiteral("widget_66"));
        widget_66->setGeometry(QRect(320, 560, 40, 40));
        widget_66->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_67 = new QWidget(level1);
        widget_67->setObjectName(QStringLiteral("widget_67"));
        widget_67->setGeometry(QRect(560, 560, 40, 40));
        widget_67->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_68 = new QWidget(level1);
        widget_68->setObjectName(QStringLiteral("widget_68"));
        widget_68->setGeometry(QRect(360, 560, 40, 40));
        widget_68->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_69 = new QWidget(level1);
        widget_69->setObjectName(QStringLiteral("widget_69"));
        widget_69->setGeometry(QRect(400, 400, 40, 40));
        widget_69->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_70 = new QWidget(level1);
        widget_70->setObjectName(QStringLiteral("widget_70"));
        widget_70->setGeometry(QRect(320, 520, 40, 40));
        widget_70->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_71 = new QWidget(level1);
        widget_71->setObjectName(QStringLiteral("widget_71"));
        widget_71->setGeometry(QRect(320, 480, 40, 40));
        widget_71->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_72 = new QWidget(level1);
        widget_72->setObjectName(QStringLiteral("widget_72"));
        widget_72->setGeometry(QRect(400, 480, 40, 40));
        widget_72->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_73 = new QWidget(level1);
        widget_73->setObjectName(QStringLiteral("widget_73"));
        widget_73->setGeometry(QRect(440, 480, 40, 40));
        widget_73->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_74 = new QWidget(level1);
        widget_74->setObjectName(QStringLiteral("widget_74"));
        widget_74->setGeometry(QRect(480, 480, 40, 40));
        widget_74->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_75 = new QWidget(level1);
        widget_75->setObjectName(QStringLiteral("widget_75"));
        widget_75->setGeometry(QRect(520, 480, 40, 40));
        widget_75->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_76 = new QWidget(level1);
        widget_76->setObjectName(QStringLiteral("widget_76"));
        widget_76->setGeometry(QRect(480, 280, 40, 40));
        widget_76->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_77 = new QWidget(level1);
        widget_77->setObjectName(QStringLiteral("widget_77"));
        widget_77->setGeometry(QRect(320, 440, 40, 40));
        widget_77->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_78 = new QWidget(level1);
        widget_78->setObjectName(QStringLiteral("widget_78"));
        widget_78->setGeometry(QRect(400, 440, 40, 40));
        widget_78->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_79 = new QWidget(level1);
        widget_79->setObjectName(QStringLiteral("widget_79"));
        widget_79->setGeometry(QRect(440, 400, 40, 40));
        widget_79->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_80 = new QWidget(level1);
        widget_80->setObjectName(QStringLiteral("widget_80"));
        widget_80->setGeometry(QRect(560, 400, 40, 40));
        widget_80->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_81 = new QWidget(level1);
        widget_81->setObjectName(QStringLiteral("widget_81"));
        widget_81->setGeometry(QRect(560, 440, 40, 40));
        widget_81->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_82 = new QWidget(level1);
        widget_82->setObjectName(QStringLiteral("widget_82"));
        widget_82->setGeometry(QRect(320, 360, 40, 40));
        widget_82->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_83 = new QWidget(level1);
        widget_83->setObjectName(QStringLiteral("widget_83"));
        widget_83->setGeometry(QRect(560, 480, 40, 40));
        widget_83->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_84 = new QWidget(level1);
        widget_84->setObjectName(QStringLiteral("widget_84"));
        widget_84->setGeometry(QRect(320, 320, 40, 40));
        widget_84->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_85 = new QWidget(level1);
        widget_85->setObjectName(QStringLiteral("widget_85"));
        widget_85->setGeometry(QRect(480, 400, 40, 40));
        widget_85->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_86 = new QWidget(level1);
        widget_86->setObjectName(QStringLiteral("widget_86"));
        widget_86->setGeometry(QRect(320, 400, 40, 40));
        widget_86->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_87 = new QWidget(level1);
        widget_87->setObjectName(QStringLiteral("widget_87"));
        widget_87->setGeometry(QRect(240, 440, 40, 40));
        widget_87->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_88 = new QWidget(level1);
        widget_88->setObjectName(QStringLiteral("widget_88"));
        widget_88->setGeometry(QRect(160, 480, 40, 40));
        widget_88->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_89 = new QWidget(level1);
        widget_89->setObjectName(QStringLiteral("widget_89"));
        widget_89->setGeometry(QRect(80, 440, 40, 40));
        widget_89->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_90 = new QWidget(level1);
        widget_90->setObjectName(QStringLiteral("widget_90"));
        widget_90->setGeometry(QRect(80, 480, 40, 40));
        widget_90->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_91 = new QWidget(level1);
        widget_91->setObjectName(QStringLiteral("widget_91"));
        widget_91->setGeometry(QRect(520, 80, 40, 40));
        widget_91->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_92 = new QWidget(level1);
        widget_92->setObjectName(QStringLiteral("widget_92"));
        widget_92->setGeometry(QRect(280, 200, 40, 40));
        widget_92->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_93 = new QWidget(level1);
        widget_93->setObjectName(QStringLiteral("widget_93"));
        widget_93->setGeometry(QRect(640, 440, 40, 40));
        widget_93->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_94 = new QWidget(level1);
        widget_94->setObjectName(QStringLiteral("widget_94"));
        widget_94->setGeometry(QRect(760, 480, 40, 40));
        widget_94->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_95 = new QWidget(level1);
        widget_95->setObjectName(QStringLiteral("widget_95"));
        widget_95->setGeometry(QRect(640, 360, 40, 40));
        widget_95->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_96 = new QWidget(level1);
        widget_96->setObjectName(QStringLiteral("widget_96"));
        widget_96->setGeometry(QRect(640, 520, 40, 40));
        widget_96->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_97 = new QWidget(level1);
        widget_97->setObjectName(QStringLiteral("widget_97"));
        widget_97->setGeometry(QRect(640, 480, 40, 40));
        widget_97->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_98 = new QWidget(level1);
        widget_98->setObjectName(QStringLiteral("widget_98"));
        widget_98->setGeometry(QRect(760, 560, 40, 40));
        widget_98->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_99 = new QWidget(level1);
        widget_99->setObjectName(QStringLiteral("widget_99"));
        widget_99->setGeometry(QRect(280, 160, 40, 40));
        widget_99->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_100 = new QWidget(level1);
        widget_100->setObjectName(QStringLiteral("widget_100"));
        widget_100->setGeometry(QRect(280, 40, 40, 40));
        widget_100->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_101 = new QWidget(level1);
        widget_101->setObjectName(QStringLiteral("widget_101"));
        widget_101->setGeometry(QRect(520, 40, 40, 40));
        widget_101->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_102 = new QWidget(level1);
        widget_102->setObjectName(QStringLiteral("widget_102"));
        widget_102->setGeometry(QRect(200, 480, 40, 40));
        widget_102->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_103 = new QWidget(level1);
        widget_103->setObjectName(QStringLiteral("widget_103"));
        widget_103->setGeometry(QRect(360, 320, 40, 40));
        widget_103->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_104 = new QWidget(level1);
        widget_104->setObjectName(QStringLiteral("widget_104"));
        widget_104->setGeometry(QRect(160, 360, 40, 40));
        widget_104->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_105 = new QWidget(level1);
        widget_105->setObjectName(QStringLiteral("widget_105"));
        widget_105->setGeometry(QRect(520, 280, 40, 40));
        widget_105->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_106 = new QWidget(level1);
        widget_106->setObjectName(QStringLiteral("widget_106"));
        widget_106->setGeometry(QRect(640, 400, 40, 40));
        widget_106->setStyleSheet(QStringLiteral("border-image: url(:/Image/wall.jpg);"));
        widget_107 = new QWidget(level1);
        widget_107->setObjectName(QStringLiteral("widget_107"));
        widget_107->setGeometry(QRect(400, 320, 40, 40));
        widget_107->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_108 = new QWidget(level1);
        widget_108->setObjectName(QStringLiteral("widget_108"));
        widget_108->setGeometry(QRect(0, 120, 40, 40));
        widget_108->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_109 = new QWidget(level1);
        widget_109->setObjectName(QStringLiteral("widget_109"));
        widget_109->setGeometry(QRect(0, 0, 40, 40));
        widget_109->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_110 = new QWidget(level1);
        widget_110->setObjectName(QStringLiteral("widget_110"));
        widget_110->setGeometry(QRect(0, 80, 40, 40));
        widget_110->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_111 = new QWidget(level1);
        widget_111->setObjectName(QStringLiteral("widget_111"));
        widget_111->setGeometry(QRect(0, 160, 40, 40));
        widget_111->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_112 = new QWidget(level1);
        widget_112->setObjectName(QStringLiteral("widget_112"));
        widget_112->setGeometry(QRect(0, 200, 40, 40));
        widget_112->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_113 = new QWidget(level1);
        widget_113->setObjectName(QStringLiteral("widget_113"));
        widget_113->setGeometry(QRect(0, 280, 40, 40));
        widget_113->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_114 = new QWidget(level1);
        widget_114->setObjectName(QStringLiteral("widget_114"));
        widget_114->setGeometry(QRect(0, 360, 40, 40));
        widget_114->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_115 = new QWidget(level1);
        widget_115->setObjectName(QStringLiteral("widget_115"));
        widget_115->setGeometry(QRect(0, 240, 40, 40));
        widget_115->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_116 = new QWidget(level1);
        widget_116->setObjectName(QStringLiteral("widget_116"));
        widget_116->setGeometry(QRect(0, 320, 40, 40));
        widget_116->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_117 = new QWidget(level1);
        widget_117->setObjectName(QStringLiteral("widget_117"));
        widget_117->setGeometry(QRect(0, 400, 40, 40));
        widget_117->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_118 = new QWidget(level1);
        widget_118->setObjectName(QStringLiteral("widget_118"));
        widget_118->setGeometry(QRect(0, 440, 40, 40));
        widget_118->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_119 = new QWidget(level1);
        widget_119->setObjectName(QStringLiteral("widget_119"));
        widget_119->setGeometry(QRect(80, 280, 40, 40));
        widget_119->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_120 = new QWidget(level1);
        widget_120->setObjectName(QStringLiteral("widget_120"));
        widget_120->setGeometry(QRect(200, 120, 40, 40));
        widget_120->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_121 = new QWidget(level1);
        widget_121->setObjectName(QStringLiteral("widget_121"));
        widget_121->setGeometry(QRect(160, 400, 40, 40));
        widget_121->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_122 = new QWidget(level1);
        widget_122->setObjectName(QStringLiteral("widget_122"));
        widget_122->setGeometry(QRect(320, 40, 40, 40));
        widget_122->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_123 = new QWidget(level1);
        widget_123->setObjectName(QStringLiteral("widget_123"));
        widget_123->setGeometry(QRect(760, 160, 40, 40));
        widget_123->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_124 = new QWidget(level1);
        widget_124->setObjectName(QStringLiteral("widget_124"));
        widget_124->setGeometry(QRect(760, 200, 40, 40));
        widget_124->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_125 = new QWidget(level1);
        widget_125->setObjectName(QStringLiteral("widget_125"));
        widget_125->setGeometry(QRect(760, 280, 40, 40));
        widget_125->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_126 = new QWidget(level1);
        widget_126->setObjectName(QStringLiteral("widget_126"));
        widget_126->setGeometry(QRect(760, 360, 40, 40));
        widget_126->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_127 = new QWidget(level1);
        widget_127->setObjectName(QStringLiteral("widget_127"));
        widget_127->setGeometry(QRect(760, 240, 40, 40));
        widget_127->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_128 = new QWidget(level1);
        widget_128->setObjectName(QStringLiteral("widget_128"));
        widget_128->setGeometry(QRect(760, 320, 40, 40));
        widget_128->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_129 = new QWidget(level1);
        widget_129->setObjectName(QStringLiteral("widget_129"));
        widget_129->setGeometry(QRect(760, 400, 40, 40));
        widget_129->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_130 = new QWidget(level1);
        widget_130->setObjectName(QStringLiteral("widget_130"));
        widget_130->setGeometry(QRect(760, 440, 40, 40));
        widget_130->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_131 = new QWidget(level1);
        widget_131->setObjectName(QStringLiteral("widget_131"));
        widget_131->setGeometry(QRect(80, 0, 40, 40));
        widget_131->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_132 = new QWidget(level1);
        widget_132->setObjectName(QStringLiteral("widget_132"));
        widget_132->setGeometry(QRect(120, 0, 40, 40));
        widget_132->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_133 = new QWidget(level1);
        widget_133->setObjectName(QStringLiteral("widget_133"));
        widget_133->setGeometry(QRect(160, 0, 40, 40));
        widget_133->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_134 = new QWidget(level1);
        widget_134->setObjectName(QStringLiteral("widget_134"));
        widget_134->setGeometry(QRect(280, 0, 40, 40));
        widget_134->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_135 = new QWidget(level1);
        widget_135->setObjectName(QStringLiteral("widget_135"));
        widget_135->setGeometry(QRect(240, 0, 40, 40));
        widget_135->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_136 = new QWidget(level1);
        widget_136->setObjectName(QStringLiteral("widget_136"));
        widget_136->setGeometry(QRect(200, 0, 40, 40));
        widget_136->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_137 = new QWidget(level1);
        widget_137->setObjectName(QStringLiteral("widget_137"));
        widget_137->setGeometry(QRect(320, 0, 40, 40));
        widget_137->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_138 = new QWidget(level1);
        widget_138->setObjectName(QStringLiteral("widget_138"));
        widget_138->setGeometry(QRect(360, 0, 40, 40));
        widget_138->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_139 = new QWidget(level1);
        widget_139->setObjectName(QStringLiteral("widget_139"));
        widget_139->setGeometry(QRect(400, 0, 40, 40));
        widget_139->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_140 = new QWidget(level1);
        widget_140->setObjectName(QStringLiteral("widget_140"));
        widget_140->setGeometry(QRect(520, 0, 40, 40));
        widget_140->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));
        widget_141 = new QWidget(level1);
        widget_141->setObjectName(QStringLiteral("widget_141"));
        widget_141->setGeometry(QRect(480, 0, 40, 40));
        widget_141->setStyleSheet(QStringLiteral("border-image: url(:/Image/block.jpg);"));

        retranslateUi(level1);

        QMetaObject::connectSlotsByName(level1);
    } // setupUi

    void retranslateUi(QWidget *level1)
    {
        level1->setWindowTitle(QApplication::translate("level1", "Form", 0));
    } // retranslateUi

};

namespace Ui {
    class level1: public Ui_level1 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LEVEL1_H
